{% set name = "gpm-api" %}
{% set version = "0.2.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/gpm_api-{{ version }}.tar.gz
  sha256: 6b210655691586dd7bb1dd0dd98ba130a94bace4f8aef9310d07536d3769ac25

build:
  entry_points:
    - download_gpm_daily_data = gpm.scripts.download_gpm_daily_data:download_gpm_daily_data
    - download_gpm_monthly_data = gpm.scripts.download_gpm_monthly_data:download_gpm_monthly_data
    - download_gpm_files = gpm.scripts.download_gpm_files:download_gpm_files
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python >=3.8
    - setuptools >=61.0.0
    - setuptools-scm >=6.2
    - wheel
    - pip
  run:
    - python >=3.8
    - xarray
    - xarray-datatree
    - netcdf4
    - dask-core
    - distributed
    - curl
    - tqdm
    - click
    - donfig
    - trollsift
    - cartopy >=0.22.0
    - matplotlib-base >=3.8.3
    - pyproj
    - scipy
    - pycolorbar
test:
  imports:
    - gpm
  commands:
    - pip check
    - download_gpm_daily_data --help
    - download_gpm_monthly_data --help
    - download_gpm_files --help
  requires:
    - pip

about:
  home: https://github.com/ghiggi/gpm_api
  summary: Python Package for the Global Precipitation Measurement (GPM) Mission Data Archive
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ghiggi
    - kmuehlbauer
