{% set name = "gpm-api" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/gpm_api-{{ version }}.tar.gz
  sha256: e4169c1fa56d380dea1e99155d4558b4fcc209c60bddb4d873da0252488f96d0

build:
  entry_points:
    - download_gpm_daily_data = gpm.scripts.download_gpm_daily_data:download_gpm_daily_data
    - download_gpm_monthly_data = gpm.scripts.download_gpm_monthly_data:download_gpm_monthly_data
    - download_gpm_files = gpm.scripts.download_gpm_files:download_gpm_files
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0.0
    - setuptools-scm >=6.2
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - xarray
    - xarray-datatree
    - xoak
    - numpy
    - pandas
    - pyyaml
    - netcdf4
    - dask-core
    - distributed
    - curl
    - tqdm
    - click
    - donfig
    - trollsift
    - cartopy >=0.22.0
    - matplotlib-base >=3.8.3
    - pyproj
    - shapely
    - geopandas
    - scipy
    - pycolorbar >=0.1.0
test:
  imports:
    - gpm
  commands:
    - pip check
    - download_gpm_daily_data --help
    - download_gpm_monthly_data --help
    - download_gpm_files --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ghiggi/gpm_api
  summary: Python Package for the Global Precipitation Measurement (GPM) Mission Data Archive
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ghiggi
    - kmuehlbauer
